version: "3.9"

services:
  dbt:
    image: dbt:1.0
    restart: always
    volumes: 
      - "./project:/root/project"
    working_dir: "/root/project"
    ports:
      - 8080:8080
    environment:
      - DBT_PROFILES_DIR=/root/project/transform-stg-sv
    profiles: ["dbt"]

networks:
  default:
    name: dbt-network