config:
  send_anonymous_usage_stats: False

staging_2:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server'
      server: 10.0.10.51
      port: 1433
      database: staging_2
      schema: dbo
      user: data_de_sa_1
      password: NNhe)TM+aMEU
      trust_cert: true
      